on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: regwael.azurecr.io
        username: ${{ secrets.acr_regwael_username }}
        password: ${{ secrets.acr_regwael_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/COPY" -f  "Dockerfile" -t regwael.azurecr.io/myakscluster:${{ github.sha }}
        docker push regwael.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclustera5be | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclustera5be`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclustera5be
        container-registry-url: regwael.azurecr.io
        container-registry-username: ${{ secrets.acr_regwael_username }}
        container-registry-password: ${{ secrets.acr_regwael_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclustera5be
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress.yml
        images: |
          regwael.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth